$source = Resolve-Path 'worker/app.ts'
$target = Join-Path (Split-Path $source) 'app-v2.ts'
$t = [IO.File]::ReadAllText($source)
$t = "import{buildPushPayload}from'@block65/webcrypto-web-push';`n" + $t
$t = $t.Replace('interface Env{DB:D1Database;COVERS:R2Bucket;ASSETS:Fetcher;ADMIN_TOKEN:string}', 'interface Env{DB:D1Database;COVERS:R2Bucket;ASSETS:Fetcher;ADMIN_TOKEN:string;VAPID_PUBLIC_KEY:string;VAPID_PRIVATE_KEY:string}')
$push = @'
async function push(e:Env,nickname:string,title:string,body:string){const rows=await e.DB.prepare('SELECT id,endpoint,p256dh,auth FROM push_subscriptions WHERE nickname=?').bind(nickname).all<any>();for(const s of rows.results)try{const payload=await buildPushPayload({data:JSON.stringify({title,body,data:{url:'/'}}),options:{ttl:86400}},{endpoint:s.endpoint,expirationTime:null,keys:{p256dh:s.p256dh,auth:s.auth}},{subject:'mailto:oscarhiishanmin26@gmail.com',publicKey:e.VAPID_PUBLIC_KEY,privateKey:e.VAPID_PRIVATE_KEY});const r=await fetch(s.endpoint,payload);if(r.status===404||r.status===410)await e.DB.prepare('DELETE FROM push_subscriptions WHERE id=?').bind(s.id).run()}catch{}}
'@
$t = $t.Replace("export default{", $push + "export default{")
$t = $t.Replace("if(p==='/admin.html')return Response.redirect(new URL('/admin-v2.html',u),302);", "if(p==='/'||p==='/index.html')return Response.redirect(new URL('/app-v3.html',u),302);if(p==='/admin.html')return Response.redirect(new URL('/admin-v3.html',u),302);")
$oldQuery = 'SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available FROM books b WHERE deleted_at IS NULL ORDER BY title'
$newQuery = 'SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.is_new isNew,b.zhuyin_group zhuyinGroup,b.pinyin_group pinyinGroup,b.stroke_count strokeCount,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available,(SELECT COUNT(*) FROM reservations r WHERE r.book_id=b.id AND r.cancelled_at IS NULL AND r.fulfilled_at IS NULL) reservationCount FROM books b WHERE deleted_at IS NULL ORDER BY title'
$t = $t.Replace($oldQuery, $newQuery)
$insert = @'
if(p==='/api/user/status'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const [l,q]=await Promise.all([e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.nickname borrowerName,l.due_at dueAt FROM loans l JOIN books b ON b.id=l.book_id WHERE l.nickname=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all(),e.DB.prepare(`SELECT r.id,r.book_id bookId,b.title bookTitle,(SELECT COUNT(*) FROM reservations x WHERE x.book_id=r.book_id AND x.created_at<=r.created_at AND x.cancelled_at IS NULL AND x.fulfilled_at IS NULL) position FROM reservations r JOIN books b ON b.id=r.book_id WHERE r.nickname=? AND r.cancelled_at IS NULL AND r.fulfilled_at IS NULL ORDER BY r.created_at`).bind(name).all()]);return J({loans:l.results,reservations:q.results})}
if(p==='/api/reservations'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.fullName||!x.nickname)return J({error:'資料不完整'},400);if(!await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return J({error:'這本書目前可直接借閱'},409);if(await e.DB.prepare('SELECT 1 FROM reservations WHERE book_id=? AND nickname=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId,x.nickname).first())return J({error:'你已經預約這本書'},409);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO reservations(id,book_id,full_name,nickname)VALUES(?,?,?,?)').bind(id,x.bookId,x.fullName,x.nickname).run();const pos=await e.DB.prepare('SELECT COUNT(*) n FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId).first<any>();return J({id,position:pos?.n||1},201)}
if(p==='/api/push/key')return J({publicKey:e.VAPID_PUBLIC_KEY});
if(p==='/api/push/subscribe'&&r.method==='POST'){const x=await data(r),s=x.subscription;if(!x.nickname||!s?.endpoint||!s.keys?.p256dh||!s.keys?.auth)return J({error:'訂閱資料不完整'},400);await e.DB.prepare(`INSERT INTO push_subscriptions(id,nickname,endpoint,p256dh,auth)VALUES(?,?,?,?,?) ON CONFLICT(endpoint)DO UPDATE SET nickname=excluded.nickname,p256dh=excluded.p256dh,auth=excluded.auth`).bind(crypto.randomUUID(),x.nickname,s.endpoint,s.keys.p256dh,s.keys.auth).run();return J({ok:true},201)}
'@
$t = $t.Replace("if(p==='/api/loans'&&r.method==='POST')", $insert + "if(p==='/api/loans'&&r.method==='POST')")
$oldReturn = "if(ret&&r.method==='POST'){await e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]).run();return J({ok:true})}"
$newReturn = "if(ret&&r.method==='POST'){const loan=await e.DB.prepare('SELECT book_id FROM loans WHERE id=?').bind(ret[1]).first<any>();await e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]).run();if(loan){const next=await e.DB.prepare('SELECT id,nickname FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL ORDER BY created_at LIMIT 1').bind(loan.book_id).first<any>();if(next){await e.DB.prepare('UPDATE reservations SET notified_at=? WHERE id=?').bind(new Date().toISOString(),next.id).run();await push(e,next.nickname,'預約書籍已可借閱','你預約的書已歸還，請儘快回到 NCKU CCC 圖書館借閱。')}}return J({ok:true})}"
$t = $t.Replace($oldReturn, $newReturn)
[IO.File]::WriteAllText($target, $t, [Text.UTF8Encoding]::new($false))
