$source=Resolve-Path 'worker/app-v2.ts';$target=Join-Path(Split-Path $source)'app-v3.ts';$t=[IO.File]::ReadAllText($source)
$helpers=@'
const ROOT='oscarhiishanmin26@gmail.com';const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b));async function hash(password:string,salt?:string){const s=salt?Uint8Array.from(atob(salt),c=>c.charCodeAt(0)):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:120000,hash:'SHA-256'},key,256);return{salt:b64(s),value:b64(new Uint8Array(bits))}}async function account(e:Env,email:string){return e.DB.prepare('SELECT email,role,password_hash passwordHash,salt,must_change mustChange,active FROM admins WHERE email=?').bind(email.toLowerCase()).first<any>()}
'@
$t=$t.Replace('async function push',$helpers.Trim()+"`nasync function push")
$old=@'
if(p==='/api/admin/login'&&r.method==='POST'){const x=await data(r),row=await e.DB.prepare("SELECT value FROM settings WHERE key='admin_email'").first<{value:string}>();if(!row||x.email?.toLowerCase()!==row.value.toLowerCase()||x.password!==e.ADMIN_TOKEN)return J({error:'Email 或密碼錯誤'},401);const id=crypto.randomUUID(),expires=new Date(Date.now()+288e5).toISOString();await e.DB.prepare('INSERT INTO admin_sessions(id,email,expires_at) VALUES(?,?,?)').bind(id,row.value,expires).run();return J({email:row.value},200,{'set-cookie':secureCookie(id)})}
'@
$new=@'
if(p==='/api/admin/login'&&r.method==='POST'){const x=await data(r),email=String(x.email||'').trim().toLowerCase();let a=await account(e,email);if(!a&&email===ROOT&&x.password===e.ADMIN_TOKEN){const h=await hash(x.password);await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,0)').bind(ROOT,'superadmin',h.value,h.salt).run();a=await account(e,email)}if(!a||!a.active)return J({error:'Email 或密碼錯誤'},401);const h=await hash(String(x.password||''),a.salt);if(h.value!==a.passwordHash)return J({error:'Email 或密碼錯誤'},401);const id=crypto.randomUUID(),expires=new Date(Date.now()+288e5).toISOString();await e.DB.prepare('INSERT INTO admin_sessions(id,email,expires_at)VALUES(?,?,?)').bind(id,email,expires).run();return J({email,role:a.role,mustChange:!!a.mustChange},200,{'set-cookie':secureCookie(id)})}
if(p==='/api/admin/forgot'&&r.method==='POST'){const x=await data(r),email=String(x.email||'').trim().toLowerCase();if(await account(e,email)&&!await e.DB.prepare("SELECT 1 FROM admin_reset_requests WHERE email=? AND status='pending'").bind(email).first())await e.DB.prepare('INSERT INTO admin_reset_requests(id,email)VALUES(?,?)').bind(crypto.randomUUID(),email).run();return J({ok:true,message:'若帳號存在，重設申請已送給最高管理員'})}
'@
$t=$t.Replace($old.Trim(),$new.Trim())
$t=$t.Replace("if(p==='/api/admin/me'){const s=await session(r,e);return s?J(s):J({error:'尚未登入'},401)}","if(p==='/api/admin/me'){const s=await session(r,e);if(!s)return J({error:'尚未登入'},401);const a=await account(e,s.email);return J({email:s.email,role:a?.role,mustChange:!!a?.mustChange})}")
$anchor="if(p==='/api/admin/dashboard'&&r.method==='GET')"
$routes=@'
if(p==='/api/admin/change-password'&&r.method==='POST'){const s=await session(r,e),x=await data(r),a=await account(e,s!.email),old=await hash(String(x.currentPassword||''),a.salt);if(old.value!==a.passwordHash)return J({error:'目前密碼不正確'},400);if(String(x.newPassword||'').length<8)return J({error:'新密碼至少需要 8 個字元'},400);const h=await hash(x.newPassword);await e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=0 WHERE email=?').bind(h.value,h.salt,s!.email).run();return J({ok:true})}
if(p==='/api/admin/admins'&&r.method==='POST'){const s=await session(r,e),me=await account(e,s!.email);if(me?.role!=='superadmin')return J({error:'只有最高管理員可以新增管理員'},403);const x=await data(r),email=String(x.email||'').trim().toLowerCase();if(!email.includes('@'))return J({error:'Email 格式不正確'},400);const h=await hash('000000');await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,1)').bind(email,'admin',h.value,h.salt).run();return J({ok:true},201)}
const adm=p.match(/^\/api\/admin\/admins\/(.+)$/);if(adm&&r.method==='DELETE'){const s=await session(r,e),me=await account(e,s!.email),email=decodeURIComponent(adm[1]).toLowerCase();if(me?.role!=='superadmin')return J({error:'權限不足'},403);if(email===ROOT)return J({error:'最高管理員不能刪除'},400);await e.DB.prepare('UPDATE admins SET active=0 WHERE email=?').bind(email).run();return J({ok:true})}
const reset=p.match(/^\/api\/admin\/resets\/([^/]+)$/);if(reset&&r.method==='POST'){const s=await session(r,e),me=await account(e,s!.email);if(me?.role!=='superadmin')return J({error:'權限不足'},403);const row=await e.DB.prepare("SELECT email FROM admin_reset_requests WHERE id=? AND status='pending'").bind(reset[1]).first<any>();if(!row)return J({error:'申請不存在'},404);const h=await hash('000000');await e.DB.batch([e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=1 WHERE email=?').bind(h.value,h.salt,row.email),e.DB.prepare("UPDATE admin_reset_requests SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?").bind(reset[1])]);return J({ok:true})}
'@
$t=$t.Replace($anchor,$routes.Trim()+$anchor)
$oldDash="return J({books:books.results,loans:loans.results,settings:Object.fromEntries(settings.results.map(v=>[v.key,v.value]))})"
$newDash="const s=await session(r,e),me=await account(e,s!.email),extra=me?.role==='superadmin'?{admins:(await e.DB.prepare('SELECT email,role,must_change mustChange,active,created_at createdAt FROM admins ORDER BY created_at').all()).results,resets:(await e.DB.prepare(`SELECT id,email,created_at createdAt FROM admin_reset_requests WHERE status='pending' ORDER BY created_at`).all()).results}:{admins:[],resets:[]};return J({books:books.results,loans:loans.results,settings:Object.fromEntries(settings.results.map(v=>[v.key,v.value])),me:{email:s!.email,role:me?.role},...extra})"
$t=$t.Replace($oldDash,$newDash)
[IO.File]::WriteAllText($target,$t,[Text.UTF8Encoding]::new($false))
