import{buildPushPayload}from'@block65/webcrypto-web-push';
interface Env{DB:D1Database;COVERS:R2Bucket;ASSETS:Fetcher;ADMIN_TOKEN:string;VAPID_PUBLIC_KEY:string;VAPID_PRIVATE_KEY:string}
const J=(x:unknown,s=200,h:HeadersInit={})=>Response.json(x,{status:s,headers:{'cache-control':'no-store',...h}});const data=(r:Request)=>r.json<any>();
const cookies=(r:Request)=>Object.fromEntries((r.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')));
async function session(r:Request,e:Env){const id=cookies(r).ccc_admin;if(!id)return null;return e.DB.prepare('SELECT email FROM admin_sessions WHERE id=? AND expires_at>?').bind(id,new Date().toISOString()).first<{email:string}>()}
const secureCookie=(id:string,max=28800)=>`ccc_admin=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${max}`;
const ROOT='oscarhiishanmin26@gmail.com';const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b));async function hash(password:string,salt?:string){const s=salt?Uint8Array.from(atob(salt),c=>c.charCodeAt(0)):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:100000,hash:'SHA-256'},key,256);return{salt:b64(s),value:b64(new Uint8Array(bits))}}async function account(e:Env,email:string){return e.DB.prepare('SELECT email,role,password_hash passwordHash,salt,must_change mustChange,active FROM admins WHERE email=?').bind(email.toLowerCase()).first<any>()}
async function push(e:Env,nickname:string,title:string,body:string){const rows=await e.DB.prepare('SELECT id,endpoint,p256dh,auth FROM push_subscriptions WHERE nickname=?').bind(nickname).all<any>();for(const s of rows.results)try{const payload=await buildPushPayload({data:JSON.stringify({title,body,data:{url:'/'}}),options:{ttl:86400}},{endpoint:s.endpoint,expirationTime:null,keys:{p256dh:s.p256dh,auth:s.auth}},{subject:'mailto:oscarhiishanmin26@gmail.com',publicKey:e.VAPID_PUBLIC_KEY,privateKey:e.VAPID_PRIVATE_KEY});const r=await fetch(s.endpoint,payload as unknown as RequestInit);if(r.status===404||r.status===410)await e.DB.prepare('DELETE FROM push_subscriptions WHERE id=?').bind(s.id).run()}catch{}}export default{async fetch(r:Request,e:Env){const u=new URL(r.url),p=u.pathname;try{
if(p==='/'||p==='/index.html')return Response.redirect(new URL('/app-v3.html',u),302);if(p==='/admin.html')return Response.redirect(new URL('/admin-v4.html',u),302);
if(p==='/api/admin/login'&&r.method==='POST'){const x=await data(r),email=String(x.email||'').trim().toLowerCase();let a=await account(e,email);if(!a&&email===ROOT&&x.password===e.ADMIN_TOKEN){const h=await hash(x.password);await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,0)').bind(ROOT,'superadmin',h.value,h.salt).run();a=await account(e,email)}if(!a||!a.active)return J({error:'Email 或密碼錯誤'},401);const h=await hash(String(x.password||''),a.salt);if(h.value!==a.passwordHash)return J({error:'Email 或密碼錯誤'},401);const id=crypto.randomUUID(),expires=new Date(Date.now()+288e5).toISOString();await e.DB.prepare('INSERT INTO admin_sessions(id,email,expires_at)VALUES(?,?,?)').bind(id,email,expires).run();return J({email,role:a.role,mustChange:!!a.mustChange},200,{'set-cookie':secureCookie(id)})}
if(p==='/api/admin/forgot'&&r.method==='POST'){const x=await data(r),email=String(x.email||'').trim().toLowerCase();if(await account(e,email)&&!await e.DB.prepare("SELECT 1 FROM admin_reset_requests WHERE email=? AND status='pending'").bind(email).first())await e.DB.prepare('INSERT INTO admin_reset_requests(id,email)VALUES(?,?)').bind(crypto.randomUUID(),email).run();return J({ok:true,message:'若帳號存在，重設申請已送給最高管理員'})}
if(p==='/api/admin/logout'&&r.method==='POST'){const id=cookies(r).ccc_admin;if(id)await e.DB.prepare('DELETE FROM admin_sessions WHERE id=?').bind(id).run();return J({ok:true},200,{'set-cookie':secureCookie('',0)})}
if(p==='/api/admin/me'){const s=await session(r,e);if(!s)return J({error:'尚未登入'},401);const a=await account(e,s.email);return J({email:s.email,role:a?.role,mustChange:!!a?.mustChange})}
if(p==='/api/books'&&r.method==='GET'){const x=await e.DB.prepare(`SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.is_new isNew,b.zhuyin_group zhuyinGroup,b.pinyin_group pinyinGroup,b.stroke_count strokeCount,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available,(SELECT COUNT(*) FROM reservations r WHERE r.book_id=b.id AND r.cancelled_at IS NULL AND r.fulfilled_at IS NULL) reservationCount FROM books b WHERE deleted_at IS NULL ORDER BY title`).all<any>();return J(x.results.map(b=>({...b,featured:!!b.featured,available:!!b.available,coverUrl:b.cover_key?`/api/covers/${b.cover_key}`:undefined})))}
if(p==='/api/settings'&&r.method==='GET'){const x=await e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>();return J(Object.fromEntries(x.results.map(v=>[v.key,v.value])))}
if(p.startsWith('/api/covers/')&&r.method==='GET'){const o=await e.COVERS.get(decodeURIComponent(p.slice(12)));if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'image/webp','cache-control':'public,max-age=3600'}})}
if(p==='/api/loans'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const x=await e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.nickname borrowerName,l.due_at dueAt FROM loans l JOIN books b ON b.id=l.book_id WHERE l.nickname=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all();return J(x.results)}
if(p==='/api/user/status'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const [l,q]=await Promise.all([e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.nickname borrowerName,l.due_at dueAt FROM loans l JOIN books b ON b.id=l.book_id WHERE l.nickname=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all(),e.DB.prepare(`SELECT r.id,r.book_id bookId,b.title bookTitle,(SELECT COUNT(*) FROM reservations x WHERE x.book_id=r.book_id AND x.created_at<=r.created_at AND x.cancelled_at IS NULL AND x.fulfilled_at IS NULL) position FROM reservations r JOIN books b ON b.id=r.book_id WHERE r.nickname=? AND r.cancelled_at IS NULL AND r.fulfilled_at IS NULL ORDER BY r.created_at`).bind(name).all()]);return J({loans:l.results,reservations:q.results})}
if(p==='/api/reservations'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.fullName||!x.nickname)return J({error:'資料不完整'},400);if(!await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return J({error:'這本書目前可直接借閱'},409);if(await e.DB.prepare('SELECT 1 FROM reservations WHERE book_id=? AND nickname=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId,x.nickname).first())return J({error:'你已經預約這本書'},409);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO reservations(id,book_id,full_name,nickname)VALUES(?,?,?,?)').bind(id,x.bookId,x.fullName,x.nickname).run();const pos=await e.DB.prepare('SELECT COUNT(*) n FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId).first<any>();return J({id,position:pos?.n||1},201)}
if(p==='/api/push/key')return J({publicKey:e.VAPID_PUBLIC_KEY});
if(p==='/api/push/subscribe'&&r.method==='POST'){const x=await data(r),s=x.subscription;if(!x.nickname||!s?.endpoint||!s.keys?.p256dh||!s.keys?.auth)return J({error:'訂閱資料不完整'},400);await e.DB.prepare(`INSERT INTO push_subscriptions(id,nickname,endpoint,p256dh,auth)VALUES(?,?,?,?,?) ON CONFLICT(endpoint)DO UPDATE SET nickname=excluded.nickname,p256dh=excluded.p256dh,auth=excluded.auth`).bind(crypto.randomUUID(),x.nickname,s.endpoint,s.keys.p256dh,s.keys.auth).run();return J({ok:true},201)}if(p==='/api/loans'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.fullName||!x.nickname)return J({error:'資料不完整'},400);if(await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return J({error:'此書已借出'},409);const queued=await e.DB.prepare('SELECT id,nickname FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL ORDER BY created_at LIMIT 1').bind(x.bookId).first<any>();if(queued&&queued.nickname!==x.nickname)return J({error:'已有預約隊伍，請等待輪到你的通知'},409);if(queued)await e.DB.prepare('UPDATE reservations SET fulfilled_at=? WHERE id=?').bind(new Date().toISOString(),queued.id).run();const id=crypto.randomUUID(),now=new Date(),due=new Date(now.getTime()+30*864e5),b=await e.DB.prepare('SELECT title FROM books WHERE id=?').bind(x.bookId).first<any>();await e.DB.prepare('INSERT INTO loans(id,book_id,full_name,nickname,borrowed_at,due_at)VALUES(?,?,?,?,?,?)').bind(id,x.bookId,x.fullName,x.nickname,now.toISOString(),due.toISOString()).run();return J({id,bookId:x.bookId,bookTitle:b?.title,borrowerName:x.nickname,dueAt:due.toISOString()},201)}
const ret=p.match(/^\/api\/loans\/([^/]+)\/return$/);if(ret&&r.method==='POST'){const loan=await e.DB.prepare('SELECT book_id FROM loans WHERE id=?').bind(ret[1]).first<any>();await e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]).run();if(loan){const next=await e.DB.prepare('SELECT id,nickname FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL ORDER BY created_at LIMIT 1').bind(loan.book_id).first<any>();if(next){await e.DB.prepare('UPDATE reservations SET notified_at=? WHERE id=?').bind(new Date().toISOString(),next.id).run();await push(e,next.nickname,'預約書籍已可借閱','你預約的書已歸還，請儘快回到 NCKU CCC 圖書館借閱。')}}return J({ok:true})}
if(p==='/api/reviews'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.name||x.rating<1||x.rating>5)return J({error:'評價資料不正確'},400);await e.DB.prepare('INSERT INTO reviews(id,book_id,name,rating,content)VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),x.bookId,x.name,x.rating,x.content||'').run();return J({ok:true},201)}
if(p.startsWith('/api/admin/')&&!await session(r,e))return J({error:'登入已過期'},401);
if(p==='/api/admin/change-password'&&r.method==='POST'){const s=await session(r,e),x=await data(r),a=await account(e,s!.email),old=await hash(String(x.currentPassword||''),a.salt);if(old.value!==a.passwordHash)return J({error:'目前密碼不正確'},400);if(String(x.newPassword||'').length<8)return J({error:'新密碼至少需要 8 個字元'},400);const h=await hash(x.newPassword);await e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=0 WHERE email=?').bind(h.value,h.salt,s!.email).run();return J({ok:true})}
if(p==='/api/admin/admins'&&r.method==='POST'){const s=await session(r,e),me=await account(e,s!.email);if(me?.role!=='superadmin')return J({error:'只有最高管理員可以新增管理員'},403);const x=await data(r),email=String(x.email||'').trim().toLowerCase();if(!email.includes('@'))return J({error:'Email 格式不正確'},400);const h=await hash('000000');await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,1)').bind(email,'admin',h.value,h.salt).run();return J({ok:true},201)}
const adm=p.match(/^\/api\/admin\/admins\/(.+)$/);if(adm&&r.method==='DELETE'){const s=await session(r,e),me=await account(e,s!.email),email=decodeURIComponent(adm[1]).toLowerCase();if(me?.role!=='superadmin')return J({error:'權限不足'},403);if(email===ROOT)return J({error:'最高管理員不能刪除'},400);await e.DB.prepare('UPDATE admins SET active=0 WHERE email=?').bind(email).run();return J({ok:true})}
const reset=p.match(/^\/api\/admin\/resets\/([^/]+)$/);if(reset&&r.method==='POST'){const s=await session(r,e),me=await account(e,s!.email);if(me?.role!=='superadmin')return J({error:'權限不足'},403);const row=await e.DB.prepare("SELECT email FROM admin_reset_requests WHERE id=? AND status='pending'").bind(reset[1]).first<any>();if(!row)return J({error:'申請不存在'},404);const h=await hash('000000');await e.DB.batch([e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=1 WHERE email=?').bind(h.value,h.salt,row.email),e.DB.prepare("UPDATE admin_reset_requests SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?").bind(reset[1])]);return J({ok:true})}if(p==='/api/admin/dashboard'&&r.method==='GET'){const [books,loans,settings]=await Promise.all([e.DB.prepare(`SELECT b.*,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available,(SELECT COUNT(*) FROM loans z WHERE z.book_id=b.id) borrowCount FROM books b WHERE deleted_at IS NULL ORDER BY created_at DESC`).all(),e.DB.prepare(`SELECT l.id,l.full_name fullName,l.nickname,b.title bookTitle,l.borrowed_at borrowedAt,l.due_at dueAt,l.returned_at returnedAt FROM loans l JOIN books b ON b.id=l.book_id ORDER BY l.borrowed_at DESC LIMIT 200`).all(),e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>()]);const s=await session(r,e),me=await account(e,s!.email),extra=me?.role==='superadmin'?{admins:(await e.DB.prepare('SELECT email,role,must_change mustChange,active,created_at createdAt FROM admins ORDER BY created_at').all()).results,resets:(await e.DB.prepare("SELECT id,email,created_at createdAt FROM admin_reset_requests WHERE status='pending' ORDER BY created_at").all()).results}:{admins:[],resets:[]};return J({books:books.results,loans:loans.results,settings:Object.fromEntries(settings.results.map(v=>[v.key,v.value])),me:{email:s!.email,role:me?.role},...extra})}
if(p==='/api/admin/books'&&r.method==='POST'){const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return J({error:'書名為必填'},400);const id=crypto.randomUUID(),pic=f.get('cover');let key:string|null=null;if(pic instanceof File&&pic.size){key=`${id}.webp`;await e.COVERS.put(key,pic.stream(),{httpMetadata:{contentType:pic.type}})}await e.DB.prepare('INSERT INTO books(id,title,author,publisher,pages,description,category,featured,is_new,cover_key)VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,title,f.get('author'),f.get('publisher'),Number(f.get('pages'))||null,f.get('description'),f.get('category'),f.get('featured')==='true'?1:0,f.get('is_new')==='true'?1:0,key).run();return J({id},201)}
const book=p.match(/^\/api\/admin\/books\/([^/]+)$/);if(book&&r.method==='PUT'){const x=await data(r);if(!x.title?.trim())return J({error:'書名為必填'},400);await e.DB.prepare('UPDATE books SET title=?,author=?,publisher=?,pages=?,description=?,category=?,featured=?,is_new=? WHERE id=?').bind(x.title,x.author||null,x.publisher||null,Number(x.pages)||null,x.description||null,x.category||null,x.featured?1:0,x.is_new?1:0,book[1]).run();return J({ok:true})}if(book&&r.method==='DELETE'){await e.DB.prepare('UPDATE books SET deleted_at=? WHERE id=?').bind(new Date().toISOString(),book[1]).run();return J({ok:true})}
if(p==='/api/admin/settings'&&r.method==='POST'){const f=await r.formData(),logo=f.get('logo');for(const key of['primary_color','accent_color','reminder_days']){const value=f.get(key);if(value)await e.DB.prepare(`INSERT INTO settings(key,value,updated_at)VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(key,String(value)).run()}if(logo instanceof File&&logo.size){await e.COVERS.put('site-logo.webp',logo.stream(),{httpMetadata:{contentType:logo.type}});await e.DB.prepare(`INSERT INTO settings(key,value)VALUES('logo_url','/api/covers/site-logo.webp') ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run()}return J({ok:true})}
return e.ASSETS.fetch(r)}catch(x){return J({error:x instanceof Error?x.message:'伺服器錯誤'},500)}},async scheduled(_c:ScheduledController,e:Env){await e.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<?').bind(new Date().toISOString()).run();const setting=await e.DB.prepare(`SELECT value FROM settings WHERE key='reminder_days'`).first<any>(),days=new Set(String(setting?.value||'3,1').split(',').map(Number)),rows=await e.DB.prepare(`SELECT l.nickname,l.due_at,b.title FROM loans l JOIN books b ON b.id=l.book_id WHERE l.returned_at IS NULL`).all<any>(),today=new Date();today.setUTCHours(0,0,0,0);for(const l of rows.results){const due=new Date(l.due_at);due.setUTCHours(0,0,0,0);const left=Math.round((due.getTime()-today.getTime())/864e5);if(days.has(left))await push(e,l.nickname,'借閱到期提醒',`《${l.title}》還有 ${left} 天到期，記得準時歸還。`)}}};
