interface Env{DB:D1Database;COVERS:R2Bucket;ASSETS:Fetcher;ADMIN_TOKEN:string}
const J=(x:unknown,s=200,h:HeadersInit={})=>Response.json(x,{status:s,headers:{'cache-control':'no-store',...h}});const data=(r:Request)=>r.json<any>();
const cookies=(r:Request)=>Object.fromEntries((r.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')));
async function session(r:Request,e:Env){const id=cookies(r).ccc_admin;if(!id)return null;return e.DB.prepare('SELECT email FROM admin_sessions WHERE id=? AND expires_at>?').bind(id,new Date().toISOString()).first<{email:string}>()}
const secureCookie=(id:string,max=28800)=>`ccc_admin=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${max}`;
export default{async fetch(r:Request,e:Env){const u=new URL(r.url),p=u.pathname;try{
if(p==='/admin.html')return Response.redirect(new URL('/admin-v2.html',u),302);
if(p==='/api/admin/login'&&r.method==='POST'){const x=await data(r),row=await e.DB.prepare("SELECT value FROM settings WHERE key='admin_email'").first<{value:string}>();if(!row||x.email?.toLowerCase()!==row.value.toLowerCase()||x.password!==e.ADMIN_TOKEN)return J({error:'Email 或密碼錯誤'},401);const id=crypto.randomUUID(),expires=new Date(Date.now()+288e5).toISOString();await e.DB.prepare('INSERT INTO admin_sessions(id,email,expires_at) VALUES(?,?,?)').bind(id,row.value,expires).run();return J({email:row.value},200,{'set-cookie':secureCookie(id)})}
if(p==='/api/admin/logout'&&r.method==='POST'){const id=cookies(r).ccc_admin;if(id)await e.DB.prepare('DELETE FROM admin_sessions WHERE id=?').bind(id).run();return J({ok:true},200,{'set-cookie':secureCookie('',0)})}
if(p==='/api/admin/me'){const s=await session(r,e);return s?J(s):J({error:'尚未登入'},401)}
if(p==='/api/books'&&r.method==='GET'){const x=await e.DB.prepare(`SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available FROM books b WHERE deleted_at IS NULL ORDER BY title`).all<any>();return J(x.results.map(b=>({...b,featured:!!b.featured,available:!!b.available,coverUrl:b.cover_key?`/api/covers/${b.cover_key}`:undefined})))}
if(p==='/api/settings'&&r.method==='GET'){const x=await e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>();return J(Object.fromEntries(x.results.map(v=>[v.key,v.value])))}
if(p.startsWith('/api/covers/')&&r.method==='GET'){const o=await e.COVERS.get(decodeURIComponent(p.slice(12)));if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'image/webp','cache-control':'public,max-age=3600'}})}
if(p==='/api/loans'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const x=await e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.nickname borrowerName,l.due_at dueAt FROM loans l JOIN books b ON b.id=l.book_id WHERE l.nickname=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all();return J(x.results)}
if(p==='/api/loans'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.fullName||!x.nickname)return J({error:'資料不完整'},400);if(await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return J({error:'此書已借出'},409);const id=crypto.randomUUID(),now=new Date(),due=new Date(now.getTime()+30*864e5),b=await e.DB.prepare('SELECT title FROM books WHERE id=?').bind(x.bookId).first<any>();await e.DB.prepare('INSERT INTO loans(id,book_id,full_name,nickname,borrowed_at,due_at)VALUES(?,?,?,?,?,?)').bind(id,x.bookId,x.fullName,x.nickname,now.toISOString(),due.toISOString()).run();return J({id,bookId:x.bookId,bookTitle:b?.title,borrowerName:x.nickname,dueAt:due.toISOString()},201)}
const ret=p.match(/^\/api\/loans\/([^/]+)\/return$/);if(ret&&r.method==='POST'){await e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]).run();return J({ok:true})}
if(p==='/api/reviews'&&r.method==='POST'){const x=await data(r);if(!x.bookId||!x.name||x.rating<1||x.rating>5)return J({error:'評價資料不正確'},400);await e.DB.prepare('INSERT INTO reviews(id,book_id,name,rating,content)VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),x.bookId,x.name,x.rating,x.content||'').run();return J({ok:true},201)}
if(p.startsWith('/api/admin/')&&!await session(r,e))return J({error:'登入已過期'},401);
if(p==='/api/admin/dashboard'&&r.method==='GET'){const [books,loans,settings]=await Promise.all([e.DB.prepare(`SELECT b.*,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available FROM books b WHERE deleted_at IS NULL ORDER BY created_at DESC`).all(),e.DB.prepare(`SELECT l.id,l.full_name fullName,l.nickname,b.title bookTitle,l.borrowed_at borrowedAt,l.due_at dueAt,l.returned_at returnedAt FROM loans l JOIN books b ON b.id=l.book_id ORDER BY l.borrowed_at DESC LIMIT 200`).all(),e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>()]);return J({books:books.results,loans:loans.results,settings:Object.fromEntries(settings.results.map(v=>[v.key,v.value]))})}
if(p==='/api/admin/books'&&r.method==='POST'){const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return J({error:'書名為必填'},400);const id=crypto.randomUUID(),pic=f.get('cover');let key:string|null=null;if(pic instanceof File&&pic.size){key=`${id}.webp`;await e.COVERS.put(key,pic.stream(),{httpMetadata:{contentType:pic.type}})}await e.DB.prepare('INSERT INTO books(id,title,author,publisher,pages,description,category,featured,cover_key)VALUES(?,?,?,?,?,?,?,?,?)').bind(id,title,f.get('author'),f.get('publisher'),Number(f.get('pages'))||null,f.get('description'),f.get('category'),f.get('featured')==='true'?1:0,key).run();return J({id},201)}
const book=p.match(/^\/api\/admin\/books\/([^/]+)$/);if(book&&r.method==='PUT'){const x=await data(r);if(!x.title?.trim())return J({error:'書名為必填'},400);await e.DB.prepare('UPDATE books SET title=?,author=?,publisher=?,pages=?,description=?,category=?,featured=? WHERE id=?').bind(x.title,x.author||null,x.publisher||null,Number(x.pages)||null,x.description||null,x.category||null,x.featured?1:0,book[1]).run();return J({ok:true})}if(book&&r.method==='DELETE'){await e.DB.prepare('UPDATE books SET deleted_at=? WHERE id=?').bind(new Date().toISOString(),book[1]).run();return J({ok:true})}
if(p==='/api/admin/settings'&&r.method==='POST'){const f=await r.formData(),logo=f.get('logo');for(const key of['primary_color','accent_color','reminder_days']){const value=f.get(key);if(value)await e.DB.prepare(`INSERT INTO settings(key,value,updated_at)VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(key,String(value)).run()}if(logo instanceof File&&logo.size){await e.COVERS.put('site-logo.webp',logo.stream(),{httpMetadata:{contentType:logo.type}});await e.DB.prepare(`INSERT INTO settings(key,value)VALUES('logo_url','/api/covers/site-logo.webp') ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run()}return J({ok:true})}
return e.ASSETS.fetch(r)}catch(x){return J({error:x instanceof Error?x.message:'伺服器錯誤'},500)}},async scheduled(_c:ScheduledController,e:Env){await e.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<?').bind(new Date().toISOString()).run()}};
