interface Env{DB:D1Database;COVERS:R2Bucket;ASSETS:Fetcher;ADMIN_TOKEN:string}
const reply=(x:unknown,status=200)=>Response.json(x,{status,headers:{'cache-control':'no-store'}});const body=async(r:Request)=>r.json<any>();const admin=(r:Request,e:Env)=>r.headers.get('authorization')===`Bearer ${e.ADMIN_TOKEN}`;
export default{async fetch(r:Request,e:Env){const u=new URL(r.url),p=u.pathname;try{
if(p==='/api/books'&&r.method==='GET'){const x=await e.DB.prepare(`SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available FROM books b WHERE deleted_at IS NULL ORDER BY title`).all<any>();return reply(x.results.map(b=>({...b,featured:!!b.featured,available:!!b.available,coverUrl:b.cover_key?`/api/covers/${b.cover_key}`:undefined})))}
if(p.startsWith('/api/covers/')&&r.method==='GET'){const o=await e.COVERS.get(decodeURIComponent(p.slice(12)));if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'image/webp','cache-control':'public,max-age=31536000,immutable'}})}
if(p==='/api/loans'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const x=await e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.nickname borrowerName,l.due_at dueAt FROM loans l JOIN books b ON b.id=l.book_id WHERE l.nickname=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all();return reply(x.results)}
if(p==='/api/loans'&&r.method==='POST'){const x=await body(r);if(!x.bookId||!x.fullName||!x.nickname)return reply({error:'資料不完整'},400);const busy=await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first();if(busy)return reply({error:'此書已借出'},409);const id=crypto.randomUUID(),now=new Date(),due=new Date(now.getTime()+30*864e5);await e.DB.prepare('INSERT INTO loans(id,book_id,full_name,nickname,borrowed_at,due_at) VALUES(?,?,?,?,?,?)').bind(id,x.bookId,x.fullName,x.nickname,now.toISOString(),due.toISOString()).run();const b=await e.DB.prepare('SELECT title FROM books WHERE id=?').bind(x.bookId).first<any>();return reply({id,bookId:x.bookId,bookTitle:b?.title,borrowerName:x.nickname,dueAt:due.toISOString()},201)}
const ret=p.match(/^\/api\/loans\/([^/]+)\/return$/);if(ret&&r.method==='POST'){await e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]).run();return reply({ok:true})}
if(p==='/api/reviews'&&r.method==='POST'){const x=await body(r);if(!x.bookId||!x.name||x.rating<1||x.rating>5)return reply({error:'評價資料不正確'},400);await e.DB.prepare('INSERT INTO reviews(id,book_id,name,rating,content) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),x.bookId,x.name,x.rating,x.content||'').run();return reply({ok:true},201)}
if(p==='/api/admin/books'&&r.method==='POST'){if(!admin(r,e))return reply({error:'管理員驗證失敗'},401);const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return reply({error:'書名為必填'},400);const id=crypto.randomUUID(),pic=f.get('cover');let key:string|null=null;if(pic instanceof File&&pic.size){key=`${id}.webp`;await e.COVERS.put(key,pic.stream(),{httpMetadata:{contentType:pic.type}})}await e.DB.prepare('INSERT INTO books(id,title,author,publisher,pages,description,category,featured,cover_key)VALUES(?,?,?,?,?,?,?,?,?)').bind(id,title,f.get('author'),f.get('publisher'),Number(f.get('pages'))||null,f.get('description'),f.get('category'),f.get('featured')==='true'?1:0,key).run();return reply({id},201)}
const del=p.match(/^\/api\/admin\/books\/([^/]+)$/);if(del&&r.method==='DELETE'){if(!admin(r,e))return reply({error:'管理員驗證失敗'},401);await e.DB.prepare('UPDATE books SET deleted_at=? WHERE id=?').bind(new Date().toISOString(),del[1]).run();return reply({ok:true})}
return e.ASSETS.fetch(r)}catch(err){return reply({error:err instanceof Error?err.message:'伺服器錯誤'},500)}},async scheduled(_c:ScheduledController,_e:Env){/* Web Push 需要 VAPID 簽章；部署步驟見 README。 */}};
