import QRCode from 'qrcode';

interface Env { DB:D1Database; COVERS:R2Bucket; ASSETS:Fetcher; ADMIN_TOKEN:string }
const ROOT='oscarhiishanmin26@gmail.com';
const json=(body:unknown,status=200,headers:HeadersInit={})=>Response.json(body,{status,headers:{'cache-control':'no-store',...headers}});
const body=(r:Request)=>r.json<any>();
const cookie=(r:Request)=>Object.fromEntries((r.headers.get('cookie')||'').split(';').map(v=>v.trim().split('=')));
const sessionCookie=(id:string,maxAge=28800)=>`ccc_admin=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${maxAge}`;
const b64=(v:Uint8Array)=>btoa(String.fromCharCode(...v));
async function hash(password:string,salt?:string){const s=salt?Uint8Array.from(atob(salt),c=>c.charCodeAt(0)):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:s,iterations:100000,hash:'SHA-256'},key,256);return{salt:b64(s),value:b64(new Uint8Array(bits))}}
async function session(r:Request,e:Env){const id=cookie(r).ccc_admin;if(!id)return null;return e.DB.prepare('SELECT email FROM admin_sessions WHERE id=? AND expires_at>?').bind(id,new Date().toISOString()).first<{email:string}>()}
async function account(e:Env,email:string){return e.DB.prepare('SELECT email,role,password_hash passwordHash,salt,must_change mustChange,active FROM admins WHERE email=?').bind(email.toLowerCase()).first<any>()}
const csvCell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows}

export default {
 async fetch(r:Request,e:Env){const u=new URL(r.url),p=u.pathname;try{
  if(p==='/api/admin/login'&&r.method==='POST'){const x=await body(r),email=String(x.email||'').trim().toLowerCase();let a=await account(e,email);if(!a&&email===ROOT&&x.password===e.ADMIN_TOKEN){const h=await hash(x.password);await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,0)').bind(ROOT,'superadmin',h.value,h.salt).run();a=await account(e,email)}if(!a||!a.active)return json({error:'Email 或密碼錯誤'},401);const h=await hash(String(x.password||''),a.salt);if(h.value!==a.passwordHash)return json({error:'Email 或密碼錯誤'},401);const id=crypto.randomUUID(),expires=new Date(Date.now()+288e5).toISOString();await e.DB.prepare('INSERT INTO admin_sessions(id,email,expires_at)VALUES(?,?,?)').bind(id,email,expires).run();return json({email,role:a.role,mustChange:!!a.mustChange},200,{'set-cookie':sessionCookie(id)})}
  if(p==='/api/admin/logout'&&r.method==='POST'){const id=cookie(r).ccc_admin;if(id)await e.DB.prepare('DELETE FROM admin_sessions WHERE id=?').bind(id).run();return json({ok:true},200,{'set-cookie':sessionCookie('',0)})}
  if(p==='/api/admin/forgot'&&r.method==='POST'){const x=await body(r),email=String(x.email||'').trim().toLowerCase();if(await account(e,email)&&!await e.DB.prepare("SELECT 1 FROM admin_reset_requests WHERE email=? AND status='pending'").bind(email).first())await e.DB.prepare('INSERT INTO admin_reset_requests(id,email)VALUES(?,?)').bind(crypto.randomUUID(),email).run();return json({ok:true,message:'若帳號存在，重設申請已送交最高管理員'})}
  if(p==='/api/admin/me'){const s=await session(r,e);if(!s)return json({error:'尚未登入'},401);const a=await account(e,s.email);return json({email:s.email,role:a?.role,mustChange:!!a?.mustChange})}
  if(p==='/api/books'&&r.method==='GET'){const x=await e.DB.prepare(`SELECT b.id,b.title,b.author,b.publisher,b.pages,b.description,b.category,b.featured,b.is_new isNew,b.zhuyin_group zhuyinGroup,b.pinyin_group pinyinGroup,b.stroke_count strokeCount,b.created_at createdAt,b.cover_key,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available,(SELECT COUNT(*) FROM reservations q WHERE q.book_id=b.id AND q.cancelled_at IS NULL AND q.fulfilled_at IS NULL) reservationCount,(SELECT ROUND(AVG(r.rating),1) FROM reviews r WHERE r.book_id=b.id) ratingAverage,(SELECT COUNT(*) FROM reviews r WHERE r.book_id=b.id) reviewCount FROM books b WHERE deleted_at IS NULL ORDER BY title`).all<any>();return json(x.results.map(v=>({...v,featured:!!v.featured,isNew:!!v.isNew,available:!!v.available,coverUrl:v.cover_key?`/api/covers/${v.cover_key}`:undefined})))}
  if(p==='/api/settings'&&r.method==='GET'){const x=await e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>();return json(Object.fromEntries(x.results.map(v=>[v.key,v.value])))}
  if(p.startsWith('/api/covers/')&&r.method==='GET'){const o=await e.COVERS.get(decodeURIComponent(p.slice(12)));return o?new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'image/webp','cache-control':'public,max-age=3600'}}):new Response('Not found',{status:404})}
  if(p==='/api/user/status'&&r.method==='GET'){const name=u.searchParams.get('name')||'';const [loans,reservations]=await Promise.all([e.DB.prepare(`SELECT l.id,l.book_id bookId,b.title bookTitle,l.full_name borrowerName,l.due_at dueAt,l.renew_count renewCount FROM loans l JOIN books b ON b.id=l.book_id WHERE l.full_name=? AND l.returned_at IS NULL ORDER BY l.due_at`).bind(name).all(),e.DB.prepare(`SELECT q.id,q.book_id bookId,b.title bookTitle,(SELECT COUNT(*) FROM reservations x WHERE x.book_id=q.book_id AND x.created_at<=q.created_at AND x.cancelled_at IS NULL AND x.fulfilled_at IS NULL) position FROM reservations q JOIN books b ON b.id=q.book_id WHERE q.full_name=? AND q.cancelled_at IS NULL AND q.fulfilled_at IS NULL ORDER BY q.created_at`).bind(name).all()]);return json({loans:loans.results,reservations:reservations.results})}
  if(p==='/api/reservations'&&r.method==='POST'){const x=await body(r);if(!x.bookId||!x.fullName)return json({error:'請填寫全名'},400);if(!await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return json({error:'此書目前可直接借閱'},409);if(await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND full_name=? AND returned_at IS NULL').bind(x.bookId,x.fullName).first())return json({error:'借閱者不能預約自己已借出的書'},409);if(await e.DB.prepare('SELECT 1 FROM reservations WHERE book_id=? AND full_name=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId,x.fullName).first())return json({error:'你已在預約隊列中'},409);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO reservations(id,book_id,full_name,nickname)VALUES(?,?,?,?)').bind(id,x.bookId,x.fullName,x.fullName).run();const n=await e.DB.prepare('SELECT COUNT(*) n FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(x.bookId).first<any>();return json({id,position:n?.n||1},201)}
  if(p==='/api/loans'&&r.method==='POST'){const admin=await session(r,e);if(!admin)return json({error:'僅管理員可辦理借閱'},401);const x=await body(r);if(!x.bookId||!x.fullName)return json({error:'請填寫全名'},400);if(await e.DB.prepare('SELECT 1 FROM loans WHERE book_id=? AND returned_at IS NULL').bind(x.bookId).first())return json({error:'書籍已借出'},409);const queued=await e.DB.prepare('SELECT id,full_name fullName FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL ORDER BY created_at LIMIT 1').bind(x.bookId).first<any>();if(queued&&queued.fullName!==x.fullName)return json({error:'此書已由其他讀者優先預約'},409);if(queued)await e.DB.prepare('UPDATE reservations SET fulfilled_at=? WHERE id=?').bind(new Date().toISOString(),queued.id).run();const id=crypto.randomUUID(),now=new Date(),due=new Date(now.getTime()+30*864e5),b=await e.DB.prepare('SELECT title FROM books WHERE id=?').bind(x.bookId).first<any>();await e.DB.prepare('INSERT INTO loans(id,book_id,full_name,nickname,borrowed_at,due_at)VALUES(?,?,?,?,?,?)').bind(id,x.bookId,x.fullName,x.fullName,now.toISOString(),due.toISOString()).run();await e.DB.prepare('INSERT INTO circulation_audit(id,action,book_id,book_title,borrower_name,admin_email)VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),'borrow',x.bookId,b?.title||null,x.fullName,admin!.email).run();return json({id,bookId:x.bookId,bookTitle:b?.title,borrowerName:x.fullName,dueAt:due.toISOString()},201)}
  const renew=p.match(/^\/api\/loans\/([^/]+)\/renew$/);if(renew&&r.method==='POST'){if(!await session(r,e))return json({error:'僅管理員可辦理續借'},401);const l=await e.DB.prepare('SELECT id,book_id bookId,due_at dueAt,renew_count renewCount FROM loans WHERE id=? AND returned_at IS NULL').bind(renew[1]).first<any>();if(!l)return json({error:'找不到借閱紀錄'},404);const left=Math.ceil((new Date(l.dueAt).getTime()-Date.now())/864e5);if(left>3)return json({error:'到期前 3 天內才可續借'},400);if(left<0)return json({error:'已逾期，請先歸還'},400);if(l.renewCount>=1)return json({error:'每次借閱限續借一次'},400);if(await e.DB.prepare('SELECT 1 FROM reservations WHERE book_id=? AND cancelled_at IS NULL AND fulfilled_at IS NULL').bind(l.bookId).first())return json({error:'已有其他讀者預約，無法續借'},409);const due=new Date(new Date(l.dueAt).getTime()+30*864e5).toISOString();await e.DB.prepare('UPDATE loans SET due_at=?,renew_count=renew_count+1 WHERE id=?').bind(due,l.id).run();return json({ok:true,dueAt:due})}
  const ret=p.match(/^\/api\/loans\/([^/]+)\/return$/);if(ret&&r.method==='POST'){const admin=await session(r,e);if(!admin)return json({error:'僅管理員可辦理歸還'},401);const loan=await e.DB.prepare('SELECT l.book_id bookId,l.full_name fullName,b.title FROM loans l JOIN books b ON b.id=l.book_id WHERE l.id=? AND l.returned_at IS NULL').bind(ret[1]).first<any>();if(!loan)return json({error:'找不到借閱紀錄'},404);await e.DB.batch([e.DB.prepare('UPDATE loans SET returned_at=? WHERE id=?').bind(new Date().toISOString(),ret[1]),e.DB.prepare('INSERT INTO circulation_audit(id,action,book_id,book_title,borrower_name,admin_email)VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),'return',loan.bookId,loan.title,loan.fullName,admin.email)]);return json({ok:true})}
  const reviews=p.match(/^\/api\/books\/([^/]+)\/reviews$/);if(reviews&&r.method==='GET'){const rows=await e.DB.prepare('SELECT id,name,rating,content,created_at createdAt FROM reviews WHERE book_id=? ORDER BY created_at DESC LIMIT 100').bind(reviews[1]).all<any>();const summary=await e.DB.prepare('SELECT ROUND(AVG(rating),1) average,COUNT(*) count FROM reviews WHERE book_id=?').bind(reviews[1]).first<any>();return json({reviews:rows.results,average:summary?.average||0,count:summary?.count||0})}if(p==='/api/reviews'&&r.method==='POST'){const x=await body(r),rating=Number(x.rating),content=String(x.content||'').trim(),name=String(x.name||'').trim();if(!x.bookId||!name||rating<1||rating>5||!Number.isInteger(rating))return json({error:'請選擇 1 到 5 星'},400);if(name.length>30)return json({error:'姓名請勿超過 30 字'},400);if(!content)return json({error:'請填寫心得內容'},400);if(content.length>1000)return json({error:'心得請勿超過 1000 字'},400);if(!await e.DB.prepare('SELECT 1 FROM books WHERE id=? AND deleted_at IS NULL').bind(x.bookId).first())return json({error:'找不到書籍'},404);await e.DB.prepare('INSERT INTO reviews(id,book_id,name,rating,content)VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),x.bookId,name,rating,content).run();return json({ok:true},201)}

  if(p.startsWith('/api/admin/')&&!await session(r,e))return json({error:'登入已失效'},401);
  if(p==='/api/admin/dashboard'&&r.method==='GET'){const [books,loans,settings,reservations,popular,month]=await Promise.all([e.DB.prepare(`SELECT b.*,NOT EXISTS(SELECT 1 FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) available,(SELECT COUNT(*) FROM loans z WHERE z.book_id=b.id) borrowCount,(SELECT l.id FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL LIMIT 1) activeLoanId,(SELECT l.full_name FROM loans l WHERE l.book_id=b.id AND l.returned_at IS NULL LIMIT 1) borrowerFullName,(SELECT q.full_name FROM reservations q WHERE q.book_id=b.id AND q.cancelled_at IS NULL AND q.fulfilled_at IS NULL ORDER BY q.created_at LIMIT 1) nextFullName FROM books b WHERE deleted_at IS NULL ORDER BY created_at DESC`).all<any>(),e.DB.prepare(`SELECT l.id,l.full_name fullName,b.title bookTitle,l.borrowed_at borrowedAt,l.due_at dueAt,l.returned_at returnedAt FROM loans l JOIN books b ON b.id=l.book_id ORDER BY l.borrowed_at DESC LIMIT 200`).all<any>(),e.DB.prepare('SELECT key,value FROM settings').all<{key:string,value:string}>(),e.DB.prepare('SELECT COUNT(*) n FROM reservations WHERE cancelled_at IS NULL AND fulfilled_at IS NULL').first<any>(),e.DB.prepare(`SELECT b.title,COUNT(l.id) borrowCount FROM books b JOIN loans l ON l.book_id=b.id WHERE b.deleted_at IS NULL GROUP BY b.id,b.title ORDER BY borrowCount DESC,b.title LIMIT 5`).all<any>(),e.DB.prepare("SELECT COUNT(*) n FROM loans WHERE borrowed_at>=date('now','start of month')").first<any>()]);const audit=(await e.DB.prepare('SELECT id,action,book_title bookTitle,borrower_name borrowerName,admin_email adminEmail,details,created_at createdAt FROM circulation_audit ORDER BY created_at DESC LIMIT 100').all<any>()).results,reviewTotal=(await e.DB.prepare('SELECT COUNT(*) n FROM reviews').first<any>())?.n||0,returnedTotal=(await e.DB.prepare('SELECT COUNT(*) n FROM loans WHERE returned_at IS NOT NULL').first<any>())?.n||0;const s=(await session(r,e))!,me=await account(e,s.email),active=loans.results.filter(v=>!v.returnedAt),stats={totalBooks:books.results.length,available:books.results.filter(v=>v.available).length,activeLoans:active.length,overdue:active.filter(v=>new Date(v.dueAt)<new Date()).length,activeReservations:reservations?.n||0,loansThisMonth:month?.n||0,returnedLoans:returnedTotal,reviews:reviewTotal};const extra=me?.role==='superadmin'?{admins:(await e.DB.prepare('SELECT email,role,must_change mustChange,active,created_at createdAt FROM admins ORDER BY created_at').all()).results,resets:(await e.DB.prepare("SELECT id,email,created_at createdAt FROM admin_reset_requests WHERE status='pending' ORDER BY created_at").all()).results}:{admins:[],resets:[]};return json({books:books.results,loans:loans.results,settings:Object.fromEntries(settings.results.map(v=>[v.key,v.value])),stats,popular:popular.results,audit,me:{email:s.email,role:me?.role},...extra})}
  if(p==='/api/admin/books/export.csv'&&r.method==='GET'){const rows=await e.DB.prepare('SELECT title,author,publisher,pages,description,category,featured,is_new,zhuyin_group,pinyin_group,stroke_count FROM books WHERE deleted_at IS NULL ORDER BY title').all<any>();const keys=['title','author','publisher','pages','description','category','featured','is_new','zhuyin_group','pinyin_group','stroke_count'];const labels=['書名','作者','出版社','頁數','簡介','分類','推薦','最新上架','注音分類','拼音分類','筆劃'];const csv='\ufeff'+[labels,...rows.results.map(v=>keys.map(k=>v[k]))].map(row=>row.map(csvCell).join(',')).join('\r\n');return new Response(csv,{headers:{'content-type':'text/csv;charset=utf-8','content-disposition':'attachment; filename="ncku-ccc-books.csv"'}})}
  if(p==='/api/admin/books/import'&&r.method==='POST'){const f=await r.formData(),file=f.get('file');if(!(file instanceof File))return json({error:'請選擇 CSV 檔案'},400);const rows=parseCsv((await file.text()).replace(/^\ufeff/,''));if(rows.length<2)return json({error:'CSV 沒有可匯入資料'},400);const aliases:Record<string,string>={'書名':'title','作者':'author','出版社':'publisher','頁數':'pages','簡介':'description','分類':'category','推薦':'featured','最新上架':'is_new','注音分類':'zhuyin_group','拼音分類':'pinyin_group','筆劃':'stroke_count'};const headers=rows[0].map(v=>aliases[v.trim()]||v.trim());let imported=0,skipped=0;for(const row of rows.slice(1)){const x=Object.fromEntries(headers.map((k,i)=>[k,row[i]?.trim()||'']));if(!x.title){skipped++;continue}await e.DB.prepare('INSERT INTO books(id,title,author,publisher,pages,description,category,featured,is_new,zhuyin_group,pinyin_group,stroke_count)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),x.title,x.author||null,x.publisher||null,Number(x.pages)||null,x.description||null,x.category||null,/^(1|true|是|yes)$/i.test(x.featured)?1:0,/^(0|false|否|no)$/i.test(x.is_new)?0:1,x.zhuyin_group||null,x.pinyin_group?.toUpperCase()||null,Number(x.stroke_count)||null).run();imported++}return json({imported,skipped},201)}
  const qr=p.match(/^\/api\/admin\/books\/([^/]+)\/qr$/);if(qr&&r.method==='GET'){const b=await e.DB.prepare('SELECT title FROM books WHERE id=? AND deleted_at IS NULL').bind(qr[1]).first<any>();if(!b)return json({error:'找不到書籍'},404);const url=`${u.origin}/?book=${encodeURIComponent(qr[1])}`,svg=await QRCode.toString(url,{type:'svg',margin:2,width:360,errorCorrectionLevel:'M'});return new Response(`<!doctype html><meta charset="utf-8"><title>${b.title} QR Code</title><style>body{font-family:system-ui;text-align:center;padding:32px;color:#18392b}svg{max-width:360px;width:90%}button{padding:10px 20px}@media print{button{display:none}}</style><h1>${b.title}</h1>${svg}<p>${url}</p><button onclick="print()">列印</button>`,{headers:{'content-type':'text/html;charset=utf-8'}})}
  if(p==='/api/admin/books'&&r.method==='POST'){const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return json({error:'書名為必填'},400);const id=crypto.randomUUID(),pic=f.get('cover');let key:string|null=null;if(pic instanceof File&&pic.size){key=`${id}.webp`;await e.COVERS.put(key,pic.stream(),{httpMetadata:{contentType:pic.type}})}await e.DB.prepare('INSERT INTO books(id,title,author,publisher,pages,description,category,featured,is_new,cover_key)VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,title,f.get('author'),f.get('publisher'),Number(f.get('pages'))||null,f.get('description'),f.get('category'),f.get('featured')==='true'?1:0,f.get('is_new')==='true'?1:0,key).run();return json({id},201)}
  const book=p.match(/^\/api\/admin\/books\/([^/]+)$/);if(book&&r.method==='PUT'){const f=await r.formData(),title=String(f.get('title')||'').trim();if(!title)return json({error:'書名為必填'},400);const current=await e.DB.prepare('SELECT cover_key coverKey FROM books WHERE id=?').bind(book[1]).first<any>();if(!current)return json({error:'找不到書籍'},404);const pic=f.get('cover'),remove=f.get('remove_cover')==='true';let key=current.coverKey||null;if(remove&&key){await e.COVERS.delete(key);key=null}if(pic instanceof File&&pic.size){const old=key;key=`${book[1]}-${Date.now()}.webp`;await e.COVERS.put(key,pic.stream(),{httpMetadata:{contentType:pic.type}});if(old&&old!==key)await e.COVERS.delete(old)}await e.DB.prepare('UPDATE books SET title=?,author=?,publisher=?,pages=?,description=?,category=?,featured=?,is_new=?,cover_key=? WHERE id=?').bind(title,f.get('author')||null,f.get('publisher')||null,Number(f.get('pages'))||null,f.get('description')||null,f.get('category')||null,f.get('featured')==='true'?1:0,f.get('is_new')==='true'?1:0,key,book[1]).run();return json({ok:true,coverUrl:key?`/api/covers/${key}`:null})}if(book&&r.method==='DELETE'){const current=await e.DB.prepare('SELECT cover_key coverKey FROM books WHERE id=?').bind(book[1]).first<any>();if(current?.coverKey)await e.COVERS.delete(current.coverKey);await e.DB.prepare('UPDATE books SET deleted_at=?,cover_key=NULL WHERE id=?').bind(new Date().toISOString(),book[1]).run();return json({ok:true})}
  if(p==='/api/admin/maintenance/cleanup'&&r.method==='POST'){const s=(await session(r,e))!,me=await account(e,s.email);if(me?.role!=='superadmin')return json({error:'僅最高管理員可清理'},403);const x=await body(r),days=Math.max(90,Number(x.days)||365),cutoff=new Date(Date.now()-days*864e5).toISOString();const count=await e.DB.prepare('SELECT COUNT(*) n FROM loans WHERE returned_at IS NOT NULL AND returned_at<?').bind(cutoff).first<any>();await e.DB.batch([e.DB.prepare('DELETE FROM loans WHERE returned_at IS NOT NULL AND returned_at<?').bind(cutoff),e.DB.prepare('INSERT INTO circulation_audit(id,action,admin_email,details)VALUES(?,?,?,?)').bind(crypto.randomUUID(),'cleanup',s.email,`清除 ${count?.n||0} 筆、${days} 天前的已歸還紀錄`)]);return json({ok:true,deleted:count?.n||0})}
  if(p==='/api/admin/settings'&&r.method==='POST'){const f=await r.formData(),logo=f.get('logo'),old=await e.DB.prepare(`SELECT value FROM settings WHERE key='logo_url'`).first<any>();for(const key of['primary_color','accent_color','reminder_days']){const value=f.get(key);if(value)await e.DB.prepare(`INSERT INTO settings(key,value,updated_at)VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(key,String(value)).run()}if(f.get('remove_logo')==='true'){if(old?.value?.startsWith('/api/covers/'))await e.COVERS.delete(old.value.slice(12));await e.DB.prepare(`DELETE FROM settings WHERE key='logo_url'`).run()}else if(logo instanceof File&&logo.size){const key=`site-logo-${Date.now()}.webp`;await e.COVERS.put(key,logo.stream(),{httpMetadata:{contentType:logo.type}});if(old?.value?.startsWith('/api/covers/'))await e.COVERS.delete(old.value.slice(12));await e.DB.prepare(`INSERT INTO settings(key,value)VALUES('logo_url',?) ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(`/api/covers/${key}`).run()}return json({ok:true})}
  if(p==='/api/admin/change-password'&&r.method==='POST'){const s=(await session(r,e))!,x=await body(r),a=await account(e,s.email),old=await hash(String(x.currentPassword||''),a.salt);if(old.value!==a.passwordHash)return json({error:'目前密碼錯誤'},400);if(String(x.newPassword||'').length<8)return json({error:'新密碼至少 8 個字元'},400);const h=await hash(x.newPassword);await e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=0 WHERE email=?').bind(h.value,h.salt,s.email).run();return json({ok:true})}
  if(p==='/api/admin/admins'&&r.method==='POST'){const s=(await session(r,e))!,me=await account(e,s.email);if(me?.role!=='superadmin')return json({error:'僅最高管理員可新增'},403);const x=await body(r),email=String(x.email||'').trim().toLowerCase();if(!email.includes('@'))return json({error:'Email 格式不正確'},400);const h=await hash('000000');await e.DB.prepare('INSERT INTO admins(email,role,password_hash,salt,must_change)VALUES(?,?,?,?,1)').bind(email,'admin',h.value,h.salt).run();return json({ok:true},201)}
  const adm=p.match(/^\/api\/admin\/admins\/(.+)$/);if(adm&&r.method==='DELETE'){const s=(await session(r,e))!,me=await account(e,s.email),email=decodeURIComponent(adm[1]).toLowerCase();if(me?.role!=='superadmin')return json({error:'權限不足'},403);if(email===ROOT)return json({error:'最高管理員不可刪除'},400);await e.DB.prepare('UPDATE admins SET active=0 WHERE email=?').bind(email).run();return json({ok:true})}
  const reset=p.match(/^\/api\/admin\/resets\/([^/]+)$/);if(reset&&r.method==='POST'){const s=(await session(r,e))!,me=await account(e,s.email);if(me?.role!=='superadmin')return json({error:'權限不足'},403);const row=await e.DB.prepare("SELECT email FROM admin_reset_requests WHERE id=? AND status='pending'").bind(reset[1]).first<any>();if(!row)return json({error:'申請不存在'},404);const h=await hash('000000');await e.DB.batch([e.DB.prepare('UPDATE admins SET password_hash=?,salt=?,must_change=1 WHERE email=?').bind(h.value,h.salt,row.email),e.DB.prepare("UPDATE admin_reset_requests SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?").bind(reset[1])]);return json({ok:true})}
  return e.ASSETS.fetch(r)
 }catch(x){return json({error:x instanceof Error?x.message:'系統發生錯誤'},500)}},
 async scheduled(_c:ScheduledController,e:Env){await e.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<?').bind(new Date().toISOString()).run()}
};







